version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - '6831:6831/udp' # Porta para o protocolo UDP (Thrift)
      - '6832:6832/udp' # Porta para agentes remotos
      - '16686:16686' # Interface gráfica do Jaeger
      - '4318:4318' # OTLP HTTP (usado pelo OTLPTraceExporter)
      # - "4317:4317"     # OTLP gRPC
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_OTLP_HTTP_PORT=4318
      # - COLLECTOR_OTLP_GRPC_PORT=4317
